# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GSGTestRepo',
                'doc_host': 'https://gsgbills.github.io',
                'git_url': 'https://github.com/gsgbills/GSGTestRepo',
                'lib_path': 'GSGTestRepo'},
  'syms': {'GSGTestRepo.core': {'GSGTestRepo.core.foo': ('core.html#foo', 'GSGTestRepo/core.py')}}}
